import React from 'react';
import logo from './logo.svg';
import './App.css';
import { ObjectVisualizer } from 'object-visualizer/lib/object-visualizer';

const test = {
  appHasAddons: false,
  backgroundImage: null,
  catalogId: "4",
  category: "Productivity",
  contentRatings: [],
  description:
    "• Email hosting with 50 GB mailbox and custom email domain address \r\n• Hub for teamwork to connect your teams with Microsoft Teams\r\n• Desktop versions of Office applications: Outlook, Word, Excel, PowerPoint,  OneNote (plus Access and Publisher for PC only) \r\n• File storage and sharing with 1 TB of OneDrive storage \r\n• One license covers fully-installed, always-up-to-date Office apps on 5 phones, 5 tablets, and 5 PCs or Macs per user \r\n• 24/7 phone and web support\r\n\r\nCompatible with Windows 10, Windows 8.1, Windows 7 Service Pack 1, and the two most recent versions of macOS. All languages included.",
  eligibleProductSkuDetails: [
    {
      availabilityId: "CFQ7TTC0K5JC",
      productId: "CFQ7TTC0K5J7",
      skuId: "0004",
      cstmSkuId: "0004",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 12.5,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "Yearly",
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "b8223c6c-5717-4564-8ed1-a46bf9b0e30a"
        }
      ],
      billingCycle: 1,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 12.5,
      formattedMSRP: null,
      paymentCadence: "Monthly",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K5KP",
      productId: "CFQ7TTC0K5J7",
      skuId: "0003",
      cstmSkuId: "0003",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 15,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "Monthly",
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "e3254b63-3660-4ed4-9bb8-5d8cbd3aaae0"
        }
      ],
      billingCycle: 1,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 15,
      formattedMSRP: null,
      paymentCadence: "Monthly",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K59C",
      productId: "CFQ7TTC0K5J7",
      skuId: "0005",
      cstmSkuId: "0005",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 150,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "Yearly",
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "b8223c6c-5717-4564-8ed1-a46bf9b0e30a"
        }
      ],
      billingCycle: 2,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 150,
      formattedMSRP: null,
      paymentCadence: "Annually",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K5B4",
      productId: "CFQ7TTC0K5J7",
      skuId: "0002",
      cstmSkuId: "0002",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 0,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "None",
      isTrial: true,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "467eab54-127b-42d3-b046-3844b860bebf"
        }
      ],
      billingCycle: 0,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 25,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 0,
      formattedMSRP: null,
      paymentCadence: "None",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K6H9",
      productId: "CFQ7TTC0K5J7",
      skuId: "0001",
      cstmSkuId: "0001",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description: "Ownership SKU",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: null,
      formattedPrice: null,
      currencyCode: null,
      recurrencePolicy: null,
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [],
      billingCycle: 0,
      maximumPurchaseQuantity: null,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Ownership SKU",
      lacksPurchaseAction: true,
      msrp: null,
      formattedMSRP: null,
      paymentCadence: "None",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    }
  ],
  hardwareProperties: null,
  iconImage: {
    uri: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4sQFM?w=180&h=180&q=60",
    location: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4sQFM?w=180&h=180&q=60",
    imagePurpose: "logo",
    height: "1555",
    width: "1555",
    caption: null,
    foregroundColor: null,
    backgroundColor: "#FFFFFF",
    fileSize: 0,
    positionInfo: null
  },
  images: [
    {
      uri: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4sQFM?ver=34f7",
      location: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4sQFM?ver=34f7",
      imagePurpose: "logo",
      height: "1555",
      width: "1555",
      caption: null,
      foregroundColor: null,
      backgroundColor: "#FFFFFF",
      fileSize: 0,
      positionInfo: null
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.61211.4294967296.f9d72514-b9c5-4116-960f-1d732f5111b3.219998a8-1325-4d21-9a50-8bff003640cd",
      location:
        "//store-images.s-microsoft.com/image/apps.61211.4294967296.f9d72514-b9c5-4116-960f-1d732f5111b3.219998a8-1325-4d21-9a50-8bff003640cd",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "Word",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/1"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.24845.4294967296.86721013-a2df-4966-b2db-bd5d2aa9f4ed.90e7c6a1-f072-4448-876b-57e9e3f3d3d7",
      location:
        "//store-images.s-microsoft.com/image/apps.24845.4294967296.86721013-a2df-4966-b2db-bd5d2aa9f4ed.90e7c6a1-f072-4448-876b-57e9e3f3d3d7",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "Excel",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/2"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.9200.4294967296.222cf001-73ce-431e-9725-13ec48d75819.5cf28edc-0653-4901-a0c7-9d669da39176",
      location:
        "//store-images.s-microsoft.com/image/apps.9200.4294967296.222cf001-73ce-431e-9725-13ec48d75819.5cf28edc-0653-4901-a0c7-9d669da39176",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "Outlook",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/3"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.57466.4294967296.6b939bdf-8663-4ef5-9f54-fff8b743ff95.0a940674-cdfc-41ca-a697-8eea92ff73b6",
      location:
        "//store-images.s-microsoft.com/image/apps.57466.4294967296.6b939bdf-8663-4ef5-9f54-fff8b743ff95.0a940674-cdfc-41ca-a697-8eea92ff73b6",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "Skype for Business",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/4"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.1619.4294967296.ea5dc37f-0fde-43ab-9e63-0c49e24dc17e.7f0fcd39-3096-4a82-8d78-a5da097bf3e9",
      location:
        "//store-images.s-microsoft.com/image/apps.1619.4294967296.ea5dc37f-0fde-43ab-9e63-0c49e24dc17e.7f0fcd39-3096-4a82-8d78-a5da097bf3e9",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "SharePoint",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/5"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.18533.4294967296.5267664f-4468-487c-ae5f-3d0c27a3843c.e8cccd36-e502-4245-a1bc-d7985bdb47e6",
      location:
        "//store-images.s-microsoft.com/image/apps.18533.4294967296.5267664f-4468-487c-ae5f-3d0c27a3843c.e8cccd36-e502-4245-a1bc-d7985bdb47e6",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "OWA",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/6"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.6094.4294967296.7c9fc54c-2fd1-4437-bc90-441e610e1bb3.97111988-d2fc-4d7f-a0f3-285001db780a",
      location:
        "//store-images.s-microsoft.com/image/apps.6094.4294967296.7c9fc54c-2fd1-4437-bc90-441e610e1bb3.97111988-d2fc-4d7f-a0f3-285001db780a",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "PowerPoint",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/7"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.19432.4294967296.9f3041d5-47a6-46e7-a58b-09ba9870dd92.8b4b0e28-359e-4583-b56b-93fa15cdd8f7",
      location:
        "//store-images.s-microsoft.com/image/apps.19432.4294967296.9f3041d5-47a6-46e7-a58b-09ba9870dd92.8b4b0e28-359e-4583-b56b-93fa15cdd8f7",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "Outlook Calendar",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/8"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.3849.4294967296.67eea20f-d519-4eb2-bfe8-13c0a5935835.d1cc78af-5207-42c2-ab44-23fe6030cc38",
      location:
        "//store-images.s-microsoft.com/image/apps.3849.4294967296.67eea20f-d519-4eb2-bfe8-13c0a5935835.d1cc78af-5207-42c2-ab44-23fe6030cc38",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "OneDrive for Business",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/9"
    },
    {
      uri:
        "//store-images.s-microsoft.com/image/apps.15344.4294967296.93a4c6f9-7aef-4d27-aaf5-37d5c362cff3.a899ed84-9e58-4cfe-9a02-b57beac3efd6",
      location:
        "//store-images.s-microsoft.com/image/apps.15344.4294967296.93a4c6f9-7aef-4d27-aaf5-37d5c362cff3.a899ed84-9e58-4cfe-9a02-b57beac3efd6",
      imagePurpose: "screenshot",
      height: "768",
      width: "1366",
      caption: "Teams",
      foregroundColor: null,
      backgroundColor: "#DC3C00",
      fileSize: 0,
      positionInfo: "Desktop/10"
    },
    {
      uri: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE2vv0c?ver=3e63",
      location: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE2vv0c?ver=3e63",
      imagePurpose: "hero",
      height: "1200",
      width: "2400",
      caption: "Man and woman on Surface in office",
      foregroundColor: "",
      backgroundColor: "",
      fileSize: 1095041,
      positionInfo: ""
    }
  ],
  productId: "CFQ7TTC0K5J7",
  id: "CFQ7TTC0K5J7",
  productSkuDetails: [
    {
      availabilityId: "CFQ7TTC0K5JC",
      productId: "CFQ7TTC0K5J7",
      skuId: "0004",
      cstmSkuId: "0004",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 12.5,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "Yearly",
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "b8223c6c-5717-4564-8ed1-a46bf9b0e30a"
        }
      ],
      billingCycle: 1,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 12.5,
      formattedMSRP: null,
      paymentCadence: "Monthly",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K5KP",
      productId: "CFQ7TTC0K5J7",
      skuId: "0003",
      cstmSkuId: "0003",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 15,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "Monthly",
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "e3254b63-3660-4ed4-9bb8-5d8cbd3aaae0"
        }
      ],
      billingCycle: 1,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 15,
      formattedMSRP: null,
      paymentCadence: "Monthly",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K59C",
      productId: "CFQ7TTC0K5J7",
      skuId: "0005",
      cstmSkuId: "0005",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 150,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "Yearly",
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "b8223c6c-5717-4564-8ed1-a46bf9b0e30a"
        }
      ],
      billingCycle: 2,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 150,
      formattedMSRP: null,
      paymentCadence: "Annually",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K5B4",
      productId: "CFQ7TTC0K5J7",
      skuId: "0002",
      cstmSkuId: "0002",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description:
        "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat. For businesses with up to 300 employees.",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: 0,
      formattedPrice: null,
      currencyCode: "USD",
      recurrencePolicy: "None",
      isTrial: true,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [
        {
          applicableMarkets: [
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW"
          ],
          idType: "OmsOfferId",
          value: "467eab54-127b-42d3-b046-3844b860bebf"
        }
      ],
      billingCycle: 0,
      maximumPurchaseQuantity: 300,
      minimumPurchaseQuantity: 25,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Sku Title",
      lacksPurchaseAction: false,
      msrp: 0,
      formattedMSRP: null,
      paymentCadence: "None",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    },
    {
      availabilityId: "CFQ7TTC0K6H9",
      productId: "CFQ7TTC0K5J7",
      skuId: "0001",
      cstmSkuId: "0001",
      cstmIsViral: false,
      isDepartmentalEligible: false,
      aadSkuId: null,
      title: "Online",
      description: "Ownership SKU",
      type: "EnterpriseOnline",
      skuDetailType: "EnterpriseOnline",
      price: null,
      formattedPrice: null,
      currencyCode: null,
      recurrencePolicy: null,
      isTrial: false,
      installationTerms: null,
      privacyPolicyUri: null,
      additionalIdentifiers: [],
      billingCycle: 0,
      maximumPurchaseQuantity: null,
      minimumPurchaseQuantity: 1,
      systemRequirements: null,
      supportedMarkets: [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ],
      iconImage: null,
      backgroundImage: null,
      productTitle: null,
      skuTitle: "Ownership SKU",
      lacksPurchaseAction: true,
      msrp: null,
      formattedMSRP: null,
      paymentCadence: "None",
      domainSubscriptionTier: null,
      buttonTitle: null,
      bundleConfig: null,
      termUnits: null,
      requirePaymentInstrument: false,
      cstmRequirePaymentInstrument: false,
      cstmViralSkuDetails: null
    }
  ],
  supportUri: "https://support.office.com/",
  features: [],
  supportedLanguages: [
    "Afrikaans (South Africa)",
    "Amharic (Ethiopia)",
    "Arabic (U.A.E.)",
    "Arabic (Bahrain)",
    "Arabic (Algeria)",
    "Arabic (Egypt)",
    "Arabic (Iraq)",
    "Arabic (Jordan)",
    "Arabic (Kuwait)",
    "Arabic (Lebanon)",
    "Arabic (Morocco)",
    "Arabic (Oman)",
    "Arabic (Qatar)",
    "Arabic (Saudi Arabia)",
    "Arabic (Tunisia)",
    "Arabic (Yemen)",
    "Azerbaijani (Cyrillic, Azerbaijan)",
    "Azerbaijani (Latin, Azerbaijan)",
    "Belarusian (Belarus)",
    "Bulgarian (Bulgaria)",
    "Bangla",
    "Bangla (Bangladesh)",
    "Bosnian (Cyrillic, Bosnia and Herzegovina)",
    "Bosnian (Latin, Bosnia and Herzegovina)",
    "Catalan (Catalan)",
    "Czech (Czech Republic)",
    "Welsh (United Kingdom)",
    "Danish (Denmark)",
    "German (Austria)",
    "German (Switzerland)",
    "German (Germany)",
    "German (Liechtenstein)",
    "German (Luxembourg)",
    "Divehi (Maldives)",
    "Greek (Cyprus)",
    "Greek (Greece)",
    "English",
    "Unknown Locale (en-AE)",
    "English (Australia)",
    "English (Belize)",
    "English (Canada)",
    "Unknown Locale (en-DZ)",
    "English (United Kingdom)",
    "English (Hong Kong SAR)",
    "English (Ireland)",
    "English (Isle of Man)",
    "English (India)",
    "English (Jamaica)",
    "Unknown Locale (en-JO)",
    "English (Kenya)",
    "English (Malta)",
    "English (Malaysia)",
    "English (Nigeria)",
    "English (New Zealand)",
    "English (Republic of the Philippines)",
    "English (Singapore)",
    "English (Slovenia)",
    "Unknown Locale (en-SK)",
    "English (Sint Maarten)",
    "Unknown Locale (en-TH)",
    "English (Trinidad and Tobago)",
    "English (United States)",
    "English (South Africa)",
    "English (Zimbabwe)",
    "Spanish",
    "Spanish (Argentina)",
    "Spanish (Bolivia)",
    "Spanish (Chile)",
    "Spanish (Colombia)",
    "Spanish (Costa Rica)",
    "Spanish (Dominican Republic)",
    "Spanish (Ecuador)",
    "Spanish (Spain)",
    "Spanish (Guatemala)",
    "Spanish (Honduras)",
    "Spanish (Mexico)",
    "Spanish (Nicaragua)",
    "Spanish (Panama)",
    "Spanish (Peru)",
    "Spanish (Puerto Rico)",
    "Spanish (Paraguay)",
    "Spanish (El Salvador)",
    "Spanish (United States)",
    "Spanish (Uruguay)",
    "Spanish (Bolivarian Republic of Venezuela)",
    "Estonian (Estonia)",
    "Basque (Basque)",
    "Finnish (Finland)",
    "Filipino (Philippines)",
    "Faroese (Faroe Islands)",
    "French",
    "French (Belgium)",
    "French (Canada)",
    "French (Switzerland)",
    "French (Algeria)",
    "French (France)",
    "French (Luxembourg)",
    "French (Morocco)",
    "French (Monaco)",
    "French (Saint Martin)",
    "Unknown Locale (fr-NR)",
    "French (Tunisia)",
    "Galician (Galician)",
    "Hausa (Latin, Nigeria)",
    "Hebrew (Israel)",
    "Hindi (India)",
    "Croatian (Latin, Bosnia and Herzegovina)",
    "Croatian (Croatia)",
    "Hungarian (Hungary)",
    "Armenian (Armenia)",
    "Indonesian (Indonesia)",
    "Igbo (Nigeria)",
    "Icelandic (Iceland)",
    "Italian (Switzerland)",
    "Italian (Italy)",
    "Japanese (Japan)",
    "Georgian (Georgia)",
    "Kazakh (Kazakhstan)",
    "Greenlandic (Greenland)",
    "Khmer (Cambodia)",
    "Korean (Korea)",
    "Kyrgyz (Kyrgyzstan)",
    "Lao (Lao P.D.R.)",
    "Lithuanian (Lithuania)",
    "Latvian (Latvia)",
    "Macedonian (Former Yugoslav Republic of Macedonia)",
    "Mongolian (Cyrillic, Mongolia)",
    "Marathi (India)",
    "Malay (Brunei Darussalam)",
    "Malay (Malaysia)",
    "Maltese (Malta)",
    "Norwegian, Bokmål (Norway)",
    "Nepali (Nepal)",
    "Dutch",
    "Dutch (Belgium)",
    "Dutch (Netherlands)",
    "Norwegian, Nynorsk (Norway)",
    "Polish (Poland)",
    "Dari (Afghanistan)",
    "Pashto (Afghanistan)",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Romanian (Romania)",
    "Russian (Belarus)",
    "Russian (Kazakhstan)",
    "Russian (Russia)",
    "Russian (Ukraine)",
    "Kinyarwanda (Rwanda)",
    "Sanskrit (India)",
    "Sinhala (Sri Lanka)",
    "Slovak (Slovakia)",
    "Slovenian (Slovenia)",
    "Albanian (Albania)",
    "Serbian (Cyrillic, Bosnia and Herzegovina)",
    "Serbian (Cyrillic, Montenegro)",
    "Serbian (Cyrillic, Serbia)",
    "Serbian (Latin, Bosnia and Herzegovina)",
    "Serbian (Latin, Montenegro)",
    "Serbian (Latin, Serbia)",
    "Swedish (Finland)",
    "Swedish (Sweden)",
    "Kiswahili (Kenya)",
    "Tamil (India)",
    "Tajik (Cyrillic, Tajikistan)",
    "Thai (Thailand)",
    "Turkmen (Turkmenistan)",
    "Turkish (Cyprus)",
    "Turkish (Turkey)",
    "Tatar (Russia)",
    "Ukrainian (Ukraine)",
    "Urdu (Islamic Republic of Pakistan)",
    "Uzbek (Cyrillic, Uzbekistan)",
    "Uzbek (Latin, Uzbekistan)",
    "Vietnamese (Vietnam)",
    "Wolof (Senegal)",
    "Yoruba (Nigeria)",
    "Chinese (Simplified, PRC)",
    "Chinese (Traditional, Hong Kong S.A.R.)",
    "Chinese (Traditional, Macao S.A.R.)",
    "Chinese (Simplified, Singapore)",
    "Chinese (Traditional, Taiwan)"
  ],
  supportedProcessors: [],
  supportedDevices: [0, 1, 9],
  supportedMarkets: [
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IQ",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "XK",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW"
  ],
  title: "Microsoft 365 Business Standard",
  subTitle: null,
  productImageUri: "//img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4sQFM?w=180&h=180&q=60",
  formattedMsrps: {
    cfq7ttc0k5jc: "USD12.5",
    cfq7ttc0k5kp: "USD15",
    cfq7ttc0k59c: "USD150",
    cfq7ttc0k5b4: "USD0"
  },
  formattedPrices: {
    cfq7ttc0k5jc: "USD12.5",
    cfq7ttc0k5kp: "USD15",
    cfq7ttc0k59c: "USD150",
    cfq7ttc0k5b4: "USD0"
  },
  productCategory: 0,
  publisher: "Microsoft Corporation",
  productDetailsResponse: {
    commercialSubscriptionProductCategory: 0,
    supportedMarkets: ["NEUTRAL"]
  },
  isInvitationOnly: false,
  origin: null
}

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <ObjectVisualizer data={test} expand={true} ></ObjectVisualizer>
      </header>
    </div>
  );
}

export default App;
